FORMAT: 1A

# UDeltio API
UDeltio API is a message board service

# UDeltio API Root [/api/v1.0/]


# Group OAuth

## Access Token [/oauth2/access_token]

+ Model (application/json)
    
    + Body

            {
                "access_token": "168eac76a49d0b1bd02b6f0f4893996142135e5f"
            }

### Get Access Token [POST]
+ Request (application/json)

        {
            "client_id": "***REMOVED***",
            "client_secret": "***REMOVED***",
            "grant_type": "password",
            "username": "cprimera",
            "password": "password"
        }

+ Response 200
    
    [Access Token][]


# Group Board

## Board's Posts [/api/v1.0/boards/{id}/posts]
Collection of Posts belonging to a Board.

+ Parameters
    + id (required, Number, `1`) ... ID of the Board

+ Model (application/json)

    + Body

            [
                {
                    "id": 1,
                    "user": 1,
                    "board": 1,
                    "creation_date": "2014-10-12T10:17:00Z",
                    "subject": "Test Message",
                    "content": "This is just a test message.",
                    "important": true
                }
            ]

    + Schema
    
            {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "user": {
                            "type": "number"
                        },
                        "board": {
                            "type": "number"
                        },
                        "creation_date": {
                            "type": "string"
                        },
                        "subject": {
                            "type": "string"
                        },
                        "content": {
                            "type": "string"
                        },
                        "important": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "id",
                        "user",
                        "board",
                        "creation_date",
                        "subject",
                        "content",
                        "important"
                    ]
                }
            }

### List All Posts [GET]
+ Response 200

    [Board's Posts][]


## Boards Collection [/api/v1.0/boards]
Collection of all Boards.

+ Model (application/json)

    + Body

            [
                {
                    "id": 1,
                    "name": "Rock Climbing",
                    "public": true,
                    "subscribers": [1, 2, 3],
                    "tags": [12, 42, 85]
                }
            ]

    + Schema
        
            {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "name": {
                            "type": "string"
                        },
                        "public": {
                            "type": "boolean"
                        },
                        "subscribers": {
                            "type": "array"
                        },
                        "tags": {
                            "type": "array"
                        }
                    },
                    "required": [
                        "id",
                        "name",
                        "public",
                        "subscribers",
                        "tags"
                    ]
                }
            }

### List all Boards [GET]
+ Response 200

    [Boards Collection][]

### Create a Board [POST]
+ Request (application/json)

        {
            "name": "Rock Climbing",
            "public": true
        }

+ Response 201

    [Board][]


## Board Favourited [/api/v1.0/boards/{id}/favourite]
Whether the Board has been favourited.

+ Parameters
    + id (required, Number, `1`) ... ID of the Board

+ Model (application/json)

    + Body

            {
                "favourite": true
            }

    + Schema
    
            {
                "type": "object",
                "properties": {
                    "favourite": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "favourite"
                ]
            }

### Get Favourited [GET]
+ Response 200

    [Board Favourited][]

### Make Favourite [POST]
+ Response 201

    [Board Favourited][]

### Remove Favourite [DELETE]
+ Response 204

## Board Permissions [/api/v1.0/boards/{id}/users]
The User Permissions on a Board

+ Parameters
    + id (required, Number, `1`) ... ID of the Board

+ Model (application/json)

    + Body

            [
                {
                    "id": 1,
                    "username": "cprimera",
                    "read": true,
                    "write": true,
                    "admin":true
                }
            ]

    + Schema

            {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "username": {
                            "type": "string"
                        },
                        "read": {
                            "type": "boolean"
                        },
                        "write": {
                            "type": "boolean"
                        },
                        "admin": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "id",
                        "username",
                        "read",
                        "write",
                        "admin"
                    ]
                }
            }

### Get Permissions [GET]
+ Response 200

    [Board Permissions][]

### Add new Permission [POST]
+ Request (application/json)

        {
            "username": "cprimera",
            "read": true,
            "write": true,
            "admin": true
        }

+ Response 201

    [Board Permissions][]

## Board Permission User [/api/v1.0/boards/{id}/users/{userid}]
A specific User Permissions on a Board

+ Parameters
    + id (required, Number, `1`) ... ID of the Board
    + userid (required, Number, `1`) ... ID of the User

+ Model (application/json)

    + Body

            {
                "id": 1,
                "username": "cprimera",
                "read": true,
                "write": true,
                "admin":true
            }

    + Schema

            {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "username": {
                        "type": "string"
                    },
                    "read": {
                        "type": "boolean"
                    },
                    "write": {
                        "type": "boolean"
                    },
                    "admin": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "id",
                    "username",
                    "read",
                    "write",
                    "admin"
                ]
            }

### Get Permission [GET]
+ Response 200

    [Board Permission User][]

### Update Permission [PUT]
+ Request (application/json)

        {
            "id": 1,
            "username": "cprimera",
            "read": true,
            "write": true,
            "admin": true
        }

+ Response 200

    [Board Permission User][]


## Board [/api/v1.0/boards/{id}]
A single Board object.

The Board resource has the following attributes:

- id
- name
- public
- subscribers
- tags

The *id* state is assigned by the UDeltio API at the moment of creation.


+ Parameters
    + id (required, Number, `1`) ... ID of the Board

+ Model (application/json)

    + Body

            {
                "id": 1,
                "name": "Rock Climbing",
                "public": true,
                "subscribers": [1, 2, 3],
                "tags": [12, 42, 85]
            }

    + Schema
        
            {
                "type": "object",
                "required": true,
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "name": {
                        "type": "string"
                    },
                    "public": {
                        "type": "boolean"
                    },
                    "subscribers": {
                        "type": "array"
                    },
                    "tags": {
                        "type": "array"
                    }
                },
                "required": [
                    "id",
                    "name",
                    "public",
                    "subscribers",
                    "tags"
                ]
            }

### Get Board [GET]
+ Response 200

    [Board][]


### Update Board [PUT]
+ Request (application/json)

        {
            "id": 1,
            "name": "Rock Climbing",
            "public": true,
            "subscribers": [1, 2, 3],
            "tags": [12, 42, 85]
        }

+ Response 200

    [Board][]


### Delete Board [DELETE]
+ Response 204


# Group User

## User [/api/v1.0/users/{id}]
A single User object.

The User resource has the following attributes:

- id
- username
- first_name
- last_name
- email

The *id* state is assigned by the UDeltio API at the moment of creation.

+ Parameters
    + id (required, Number, `2`) ... ID of the User

+ Model (application/json)

    JSON representation of User Resource.

    + Body

            {
                "id": 2,
                "username": "cprimera",
                "first_name": "Christopher",
                "last_name": "Primerano",
                "email": "chris.primerano@mail.utoronto.ca"
            }

    + Schema
        
            {
                "type": "object",
                "required": true,
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "username": {
                        "type": "string"
                    },
                    "first_name": {
                        "type": "string"
                    },
                    "last_name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "username",
                    "first_name",
                    "last_name",
                    "email"
                ]
            }

### Get User [GET]
+ Response 200

    [User][]

### Update User [PUT]
+ Request (application/json)
        
        {
            "id": 2,
            "username": "cprimera",
            "first_name": "Christopher",
            "last_name": "Primerano",
            "email": "chris.primerano@mail.utoronto.ca"
        }

+ Response 200
    
    [User][]

### Delete User [DELETE]
+ Response 204


## User's Posts [/api/v1.0/users/{id}/posts]
Collection of Posts belonging to a Board.

+ Parameters
    + id (required, Number, `1`) ... ID of the Board

+ Model (application/json)

    + Body

            [
                {
                    "id": 1,
                    "user": 1,
                    "board": 1,
                    "creation_date": "2014-10-12T10:17:00Z",
                    "subject": "Test Message",
                    "content": "This is just a test message.",
                    "important": true
                }
            ]

    + Schema
    
            {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "user": {
                            "type": "number"
                        },
                        "board": {
                            "type": "number"
                        },
                        "creation_date": {
                            "type": "string"
                        },
                        "subject": {
                            "type": "string"
                        },
                        "content": {
                            "type": "string"
                        },
                        "important": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "id",
                        "user",
                        "board",
                        "creation_date",
                        "subject",
                        "content",
                        "important"
                    ]
                }
            }

### List All Posts [GET]
+ Response 200

    [User's Posts][]


## User Collection [/api/v1.0/users]
Collection of all Users.

+ Model (application/json)

    + Body

            [
                {
                    "id": 2,
                    "username": "cprimera",
                    "first_name": "Christopher",
                    "last_name": "Primerano",
                    "email": "chris.primerano@mail.utoronto.ca"
                }
            ]

    + Schema
        
            {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "username": {
                            "type": "string"
                        },
                        "first_name": {
                            "type": "string"
                        },
                        "last_name": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "id",
                        "username",
                        "first_name",
                        "last_name",
                        "email"
                    ]
                }
            }

### Retrieve All Users [GET]
+ Response 200

    [User Collection][]

### Create new User [POST]
+ Request (application/json)

        {
            "username": "cprimera",
            "first_name": "Christopher",
            "last_name": "Primerano",
            "email": "chris.primerano@mail.utoronto.ca"
        }

+ Response 201

    [User][]




# Group Post

## Post [/api/v1.0/posts/{id}]
A single Post object.

The Post resource has the following attributes:

- id
- user
- board
- creation_date
- subject
- content
- important

The states *id* and *creation_date* are assigned by the UDeltio API at the moment of creation.


+ Parameters
    + id (required, Number, `1`) ... ID of the Post

+ Model (application/json)

    JSON representation of Post Resource.

    + Body

            {
                "id": 1,
                "user": 1,
                "board": 1,
                "creation_date": "2014-10-12T10:17:00Z",
                "subject": "Test Message",
                "content": "This is just a test message.",
                "important": true
            }
    
    + Schema
    
            {
                "type": "object",
                "required": true,
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "user": {
                        "type": "number"
                    },
                    "board": {
                        "type": "number"
                    },
                    "creation_date": {
                        "type": "string"
                    },
                    "subject": {
                        "type": "string"
                    },
                    "content": {
                        "type": "string"
                    },
                    "important": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "id",
                    "user",
                    "board",
                    "creation_date",
                    "subject",
                    "content",
                    "important"
                ]
            }

### Get Post [GET]
+ Response 200

    [Post][]

### Update Post [PUT]
+ Request (application/json)

        {
            "id": 1,
            "user": 1,
            "board": 1,
            "creation_date": "2014-10-12T10:17:00Z",
            "subject": "Test Message",
            "content": "This is just a test message.",
            "important": true
        }

+ Response 200

    [Post][]

### Delete Post [DELETE]
+ Response 204



## Posts Collection [/api/v1.0/posts]
Collection of all Posts.

+ Model (application/json)

    + Body

            [
                {
                    "id": 1,
                    "user": 1,
                    "board": 1,
                    "creation_date": "2014-10-12T10:17:00Z",
                    "subject": "Test Message",
                    "content": "This is just a test message.",
                    "important": true
                }
            ]

    + Schema
    
            {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "user": {
                            "type": "number"
                        },
                        "board": {
                            "type": "number"
                        },
                        "creation_date": {
                            "type": "string"
                        },
                        "subject": {
                            "type": "string"
                        },
                        "content": {
                            "type": "string"
                        },
                        "important": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "id",
                        "user",
                        "board",
                        "creation_date",
                        "subject",
                        "content",
                        "important"
                    ]
                }
            }

### List All Posts [GET]
+ Response 200

    [Posts Collection][]

### Create a Post [POST]
+ Request (application/json)

        {
            "board": 1,
            "subject": "Test Message",
            "content": "This is just a test message.",
            "important": true
        }

+ Response 201

    [Post][]





# Group Tag

## Tag [/api/v1.0/tags/{id}]
A single Tag object.

The Tag resource has the following attributes:

- id
- name

The *id* state is assigned by the UDeltio API at the moment of creation.

+ Parameters
    + id (required, Number, `1`) ... ID of the Tag

+ Model (application/json)

    JSON representation of Tag Resource.

    + Body

            {
                "id": 1,
                "name": "adventure"
            }

    + Schema
        
            {
                "type": "object",
                "required": true,
                "properties": {
                    "id": {
                        "type": "number"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name"
                ]
            }

### Get Tag [GET]
+ Response 200

    [Tag][]

### Delete Tag [DELETE]
+ Response 204

## Tag Collection [/api/v1.0/tags]
Collection of all Tags.

+ Model (application/json)

    + Body

            [
                {
                    "id": 1,
                    "name": "adventure"
                }
            ]

    + Schema
        
            {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "number"
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "id",
                        "name"
                    ]
                }
            }

### Retrieve All Tags [GET]
+ Response 200

    [Tag Collection][]

### Create new Tag [POST]
+ Request (application/json)

        {
            "name": "adventure"
        }

+ Response 201

    [Tag][]